/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownItemButton: typeof import('bootstrap-vue-next')['BDropdownItemButton']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    IBiCheck2: typeof import('~icons/bi/check2')['default']
    IBiCircleHalf: typeof import('~icons/bi/circle-half')['default']
    IBiGithub: typeof import('~icons/bi/github')['default']
    IBiMoonStarsFill: typeof import('~icons/bi/moon-stars-fill')['default']
    IBiPaypal: typeof import('~icons/bi/paypal')['default']
    IBiSunFill: typeof import('~icons/bi/sun-fill')['default']
    IBiTwitter: typeof import('~icons/bi/twitter')['default']
    IBiYoutube: typeof import('~icons/bi/youtube')['default']
    NavbarHeader: typeof import('./components/NavbarHeader.vue')['default']
  }
}
